<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/**
 * @var Link $block
 * @var Escaper $escaper
 */
?>
<?php if ($block->isPossibleOnepageCheckout()): ?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
            class="customcheckout action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()): ?>
                disabled="disabled"
            <?php endif; ?>>
        <span><?= $escaper->escapeHtml(__('Proceed to Checkout')) ?></span>
    </button>
<?php endif?>

<script>        
require([
	'jquery',
	'Magento_Customer/js/customer-data'
], function($, customerData, customer) {
	$('.customcheckout').click(function(){
		console.log('override button link');
		var cartData = customerData.get('cart');
		var params = [];
		params['data-nf-access-token'] = cartData().is_logged ? window.nofraudcheckout_accesstokenforcustomer : window.nofraudcheckout_accesstokenfornotlogin;
		params['data-nf-cart-id'] = cartData().data_id;
		params['data-nf-customer-is-logged-in'] = cartData().is_logged ? 1 : 0;
		params['data-nf-merchant-id'] = window.nofraudcheckout_merchant;
		params['data-nf-store-url'] = BASE_URL;
		
		console.log(params);
		
		nfOpenCheckout(params);
	})
})
</script>